### ISSUE TITLE
Implement support for ledger `creator` param (ledger node id)

### ISSUE THREAD

**Issue by dmitrizagidulin** [veres-one/did-veres-one#11] opened 2018-11-12 21:49 UTC

**Comment by dmitrizagidulin** [comment] 2018-11-12 21:50
Add `getLatestSummary` function to the VeresOneClient.

**Comment by dlongley** [comment] 2018-11-16 06:16
We should explore if it would be better to put `basisBlockHeight` on merge events rather than on operations... prior to implementing it anywhere.

**Comment by mattcollier** [comment] 2018-11-16 15:47
For the sake of discussion here are examples of the various records:  **note these are not related records** https://gist.github.com/mattcollier/07947fca55aeb6a13430015d795cf294

Conceptually, I like the idea of not having `basisBlockHeight` in the operation record, but I'm struggling to imagine how this might work.

The first thing that occurs to me is that if we figure out a way to not have it in the record itself, then it could be meta-data from just about anywhere.

I don't understand anything about the concept of putting `basisBlockHeight` on merge events, so please tell me more about this idea.

So, it's at the `WebLedgerOperationEvent` level that we have `meta.blockHeight`.  We can quickly and easily get from `operation.meta.eventHash` -> `event.meta.blockHeight`.  In fact, we're already doing this in the [getRecordHistory API](https://github.com/digitalbazaar/bedrock-ledger-storage-mongodb/blob/master/lib/LedgerOperationStorage.js#L97)

I know that `basisBlockHeight` aims to solve a number of issues.  Let's talk about the digital signature validation use case.

The issue is, that we have a record on the ledger that has been signed with some DID based keys.  When I go to dereference the public key, we find that the key has been revoked (for example).  

Here is `ledgerNode.record.get`: https://github.com/digitalbazaar/bedrock-ledger-node/blob/master/lib/LedgerNodeRecords.js#L35

Here is the ledger agent record query API:  https://github.com/digitalbazaar/bedrock-ledger-agent/blob/master/lib/http.js#L464

It appears to me that on for the original record query, the `meta` would include `blockHeight` information.  And if it doesn't already, that could be easily arranged.

One could then specify that `blockHeight` (from the meta data) as the `maxBlockHeight` when doing additional ledger lookups for the purposes of dereferencing keys.

I notice that the `maxBlockHeight` option available on the `ledgerNode.record.get` API has not been exposed in the `LedgerAgent` API.

I'm going to stop and let others say what they think about the meta-data approach generally.

*If* it solves this particular use case, does it help with others?

**Comment by mattcollier** [comment] 2018-11-16 16:02
In revisiting the attack mitigation document, I think the merge event idea pertains to gossip/consensus operation validation processes.  Thinking about this idea in that light now.

**Comment by dlongley** [comment] 2018-11-16 16:09
So `basisBlockHeight` could be restricted to something that the nodes use and make sure they record when generating their regular events (actually, I don't think it needs to be in merge events, but regular events ... thinking about it more). The whole point of it is to make sure that nodes evaluate operations the same way -- but they really only need to make sure they evaluate operations the same way that the *one node* that bundled the operations together into a regular event did. They would also make sure that the node's choice for `basisBlockHeight` for their regular event was valid, e.g. not too far in the past.

This could also be the basis for rejecting regular events from nodes that are trying to gossip information that is too far in the past ... and a specific message could inform them of that problem so they'd catch up and revalidate operations using a more recent `basisBlockHeight`.

Furthermore, we need to ensure that operations aren't replayed -- and if we see an operation with the same hash being played after it was accepted using some earlier `basisBlockHeight`, we could reject regular events that include it using a later `basisBlockHeight` that is beyond some window.

**Comment by dlongley** [comment] 2018-12-07 17:57
It has been decided that the term that should be used here is `creator` not `webLedgerNode`.

**Comment by mattcollier** [comment] 2019-01-09 15:58
This has been addressed in #17

**Closed by mattcollier** 2019-01-09 15:58 UTC
